### ISSUE TITLE
Remove Spaces From Bear Tags

### ISSUE THREAD

**Issue by shepster** [bernardoamc/obsidian_bear#4]
Bear allows spaces in tags (though you need a following hash to close the tag. e.g. `#chocolate milk#`).

Obsidian does not allow spaces in tags (https://help.obsidian.md/How+to/Working+with+tags), so when importing from Bear to Obsidian, I recommend modifying the tags to `snake_case` or `kebab-case`

**Comment by bernardoamc** [comment]
I did not know that, that's interesting! This might be tricky if someone has a note with something like:

```
#first_tag #second tag#
```

I will think about how to handle this one. Thanks @shepster!

**Comment by bernardoamc** [comment]
I will cut a new release, should be good now. :)
