### ISSUE TITLE
Multi-word tags at beginning of multi-tag line gain leading underscore

### ISSUE THREAD

**Issue by wlonkly** [bernardoamc/obsidian_bear#7]
Hey, thanks a lot for writing this! I've just started using Obsidian and being able to import all of my Bear notes to start with is very helpful. I had no problem getting this it to work but I found one little bug.

In [here](https://github.com/bernardoamc/obsidian_bear/blob/7d95e0b1cd00de82cac5162dc3137714fe11833c/lib/obsidian_bear/bear.rb), `extract_tags` does
```ruby
line.split(' #').map { |str| format_tag(str) }
```
and in `format_tag`, 
```ruby
str.chop.gsub(/[^\w\/]/, '_')
```
but if the first tag in `line` was a multiword tag, it still has the leading `#` (because of splitting on _space-#_), which is converted to an underscore.

Since we know it's a multiword tag at that point, I think it should be safe to
```ruby
str.gsub(/#/, '').gsub(/[^\w\/]/, '_')
```
and that looks like it takes care of it:
```ruby
irb(main):061:0> line = "#one two three# #four #five six seven# #eight"
=> "#one two three# #four #five six seven# #eight"
irb(main):062:0> line.split(' #').map { |str| format_tag(str) }
=> ["one_two_three", "four", "five_six_seven", "eight"]
```

but I'm not sure if I've missed an edge case.

(By the way, really appreciate your detailed comments, it was really easy to tell the "why" of the code.)

**Comment by bernardoamc** [comment]
Hi @wlonkly, great catch! I'm happy the project has served you well. I couldn't find something like this when I was migrating and decided to write this small project to help myself and others. :)

I have a PR open at #8, let me know if this solves the issue. I've expanded on one of the test cases to make sure I wasn't introducing any new edge cases. 😄 

> (By the way, really appreciate your detailed comments, it was really easy to tell the "why" of the code.)

My pleasure! I had to update the comments to take into account the new parsing logic, few free to share any suggestions/feedback.
